apiVersion: v1alpha
kind: cypress
defaults:
  mode: sauce
sauce:
  region: us-west-1
  concurrency: 2
  metadata:
    name: saucectl cypress example
    tags:
      - e2e
      - release team
      - other tag
    build: Github Run $GITHUB_RUN_ID
docker:
  fileTransfer: copy
cypress:
  version: 7.3.0
  configFile: "cypress.json"
rootDir: ./
suites:
  - name: "Windows Chrome"
    browser: "chrome"
    platformName: "Windows 10"
    screenResolution: "1920x1080"
    config:
      testFiles: ["**/*.*"]

artifacts:
  download:
    when: always
    match:
      - console.log
    directory: ./artifacts/
